# Generated by Django 4.2.7 on 2023-12-03 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('votes_good', models.IntegerField(default=0)),
                ('votes_bad', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
