# Generated by Django 4.2.7 on 2023-12-03 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_student',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='forum.student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_teacher',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='forum.teacher'),
        ),
    ]
